### ISSUE TITLE
Hosts File Not Updated When Changing Device Name in Settings | Details | About

### ISSUE THREAD

**Issue by Hielyr** [pop-os/systemd#5]
**Distribution (run `cat /etc/os-release`):**
 
 Pop!_OS 19.04

**Issue/Bug Description:**

When changing the device name in the "About" page, the hosts file is not updated to reflect the new name, which causes programs to respond slowly, such as when running a sudo command in a terminal window or opening pretty much any app / program. The delay is anywhere between five seconds to upwards of thirty.

Updating /etc/hosts to reflect the new name solves the problem instantly and operation returns to normal.

**Steps to reproduce (if you know):**

Change the default entry in the "Device name" field of the About page in Settings | Details to anything but the default and reboot the system to see the effects.

**Expected behavior:**

Ideally, when changing the Device name, it should update the hosts file entry to reflect this to prevent any issues.

**Comment by ids1024** [comment]
For anyone having issues with this, does installing `libnss-myhostname`  help? `/etc/hosts` is somewhat legacy at this point. It may be intentional if Gnome or systemd doesn't change it automatically.

(I'm not aware that Pop!_OS has any behavior here that differs from upstream Ubuntu/Gnome/etc., but feel free to correct me if anyone has more information.)

**Comment by Gasiyu** [comment]
> For anyone having issues with this, does installing `libnss-myhostname` help? `/etc/hosts` is somewhat legacy at this point. It may be intentional if Gnome or systemd doesn't change it automatically.
> 
> (I'm not aware that Pop!_OS has any behavior here that differs from upstream Ubuntu/Gnome/etc., but feel free to correct me if anyone has more information.)

Same, still happens

**Comment by ids1024** [comment]
After some testing:

Changing the hostname in Gnome Control Center also doesn't change `/etc/hosts` on Ubuntu 20.10. Presumably this is upstream Gnome behavior.

The current default configuration on Ubuntu and Pop!_OS uses systemd-resolved for domain resolution. It seems it resolves the system's hostname regardless of what is in `/etc/hosts`.

So I'm not aware of any issues with `/etc/hosts` not containing the systems hostname. Perhaps some software reads the file directly rather than resolving through glibc. Of course if anyone has problems editing the file manually is possible.

**Comment by TechnologyMan101** [comment]
Yes, I can confirm the above behavior. Even running `sudo hostnamectl set-hostname newhostname` will still give the same result.

**Comment by ids1024** [comment]
> Yes, I can confirm the above behavior.

"Above behavior" being the lagging response from applications, rather than just `/etc/hosts` not changing?

**Comment by TechnologyMan101** [comment]
Sorry, meant just the `/etc/hosts` not changing. And for extra information, it has occurred in every distro I ran the command on.

**Comment by i28v** [comment]
When will they fix this?

**Comment by TechnologyMan101** [comment]
You realize that this isn't even specific to Pop!_OS right? And it's also nothing that the devs here did to cause this.

**Comment by TechnologyMan101** [comment]
Whenever this is fixed really depends on systemd. I don't even think this is a major issue. I've never had any issue after changing the hostname

**Comment by jacobgkau** [comment]
When looking into this again today, it seems we might be able to fix this by enabling the `nss-myhostname` module in `/etc/nsswitch.conf`:

https://github.com/systemd/systemd/issues/12793 

https://www.freedesktop.org/software/systemd/man/nss-myhostname.html 

It looks like this would eliminate the need to have the system's specific hostname listed in `/etc/hosts`.

`/etc/nsswitch.conf` is provided by `base-files`, which currently comes from Ubuntu and is not repackaged by Pop!_OS; I would assume we could override that version of the file in https://github.com/pop-os/default-settings.

**Comment by DarkJoker360** [comment]
Hello. This issue is present on 22.04 LTS release too. 
To change hostname we need to edit /etc/hostname using cli.

**Comment by hsgg** [comment]
> [systemd/systemd#12793](https://github.com/systemd/systemd/issues/12793)

Yup, installing `libnss-myhostname` and deleting the `/etc/hosts` file (or just the pop-os entry) fixed the problem for me

(And for context: I have two laptops with pop-os installed. Better give them different names so that I can easily ssh from one to the other.)

**Comment by keithfancher** [comment]
> Yup, installing libnss-myhostname and deleting the /etc/hosts file (or just the pop-os entry) fixed the problem for me

Just another data point, this did *not* fix the issue for me. (PopOS 22.04.) The only thing that fixed it was to edit `/etc/hosts`.

Interestingly, this issue only affects me when I'm using my VPN. (Mullvad.)

> You realize that this isn't even specific to Pop!_OS right? And it's also nothing that the devs here did to cause this.

> Whenever this is fixed really depends on systemd. I don't even think this is a major issue. I've never had any issue after changing the hostname

Of course this isn't Pop's "fault", but it's still a bad experience for its users. If I hadn't stumbled upon this thread, for example, I would have just shrugged and gone back to Ubuntu, where I didn't have this issue. (Because, for whatever reason, however they do it, Ubuntu ensures that the system's host name *is* in `/etc/hosts`.) I think it's also worthwhile for PopOS to try to iron out these little kinks as much as possible, personally.

Anyway... I'm glad I *did* stumble upon this thread, and that it's an easy fix :smile: ... this has been one of the only issues I've had with Pop so far, honestly.

**Comment by redbeardymcgee** [comment]
For anyone still experiencing this issue, there is currently no fix from upstream as of the date of this comment.

Fortunately, you can simply hand-edit `/etc/hosts` and replace all instances of `pop-os` with your desired hostname. It should (must?) match the same name you applied in `Settings -> About -> Device Name` or `hostnamectl set-hostname <NEW HOSTNAME>`.

I don't know if this is a better solution that the previously noted package `libnss-myhostname`.

**Comment by jacobgkau** [comment]
We probably just need to remove the hostname from the default `/etc/hosts` config and start shipping `libnss-myhostname`. We may not be able to fix it for existing installs (without being destructive towards `/etc/hosts`), but the earlier we go ahead and change the default configuration, the sooner new installs will stop having the problem.

**Comment by jacobgkau** [comment]
I've opened https://github.com/pop-os/distinst/pull/322 to stop creating `/etc/hosts` on installation, and https://github.com/pop-os/desktop/pull/128 to install `libnss-myhostname` by default (although the latter may not actually  be necessary.)

**Comment by LucaJunge** [comment]
That bug and this thread took me about 5 hours to hunt down, but I'm glad there's a solution (now). Thank you!

**Comment by jacobgkau** [comment]
As of the 11/22 isos (v36), distinst no longer puts the hostname in `/etc/hosts` by default. This is now solved for new installations. This means new installations will not have any hostname configuration discrepancies after using `hostnamectl` or the Settings app (GNOME Control Center) to change the hostname.

Existing installations still affected can be fixed manually by removing the hostname line(s) from `/etc/hosts` (we can't fix existing installations automatically without being destructive towards that file).
